load("@rules_elixir//tools:elixir_vars.bzl", "ELIXIR_VARS_ENV_MAP")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

[sh_test(
    name = distribution + "_test",
    srcs = ["distribution_test.sh"],
    args = ["$(rootpaths @elixir_config//" + distribution + ":elixir_build)"],
    data = ["@elixir_config//" + distribution + ":elixir_build"],
    env = ELIXIR_VARS_ENV_MAP,
    toolchains = ["@rules_elixir//tools:elixir_vars"],
) for distribution in [
    "source",
    "prebuilt",
]]
