load(
    "@bazel_skylib//rules:common_settings.bzl",
    "string_flag",
)
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("//:ex_unit_test.bzl", "ex_unit_test")
load("//tools:elixir_vars.bzl", "ELIXIR_VARS_ENV_MAP")

string_flag(
    name = "elixir_home",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

sh_test(
    name = "hex_archive_test",
    srcs = ["tests/hex_archive_test.sh"],
    args = ["$(location @hex//:archive)"],
    data = ["@hex//:archive"],
    env = ELIXIR_VARS_ENV_MAP,
    toolchains = ["//tools:elixir_vars"],
)

ex_unit_test(
    name = "dependency_sync_test",
    srcs = ["tests/dependency_sync_test.exs"],
    data = ["//tools:dependency_sync.exs"],
)

string_flag(
    name = "mix_env",
    build_setting_default = "dev",
    scope = "target",
    values = [
        "dev",
        "test",
        "prod",
    ],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "mix_dev",
    flag_values = {":mix_env": "dev"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "mix_test",
    flag_values = {":mix_env": "test"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "mix_prod",
    flag_values = {":mix_env": "prod"},
    visibility = ["//visibility:public"],
)

ex_unit_test(
    name = "beam_metadata_test",
    srcs = ["tests/beam_metadata_test.exs"],
    data = ["//private:beam_metadata.ex"],
    env = {"ERL_COMPILER_OPTIONS": "deterministic"},
)
