# This file is generated by rules_elixir via the elixir_config macro

load(
    "@rules_elixir//:elixir_build.bzl",
    "elixir_prebuilt",
)
load(
    "@rules_elixir//:elixir_toolchain.bzl",
    "elixir_toolchain",
)

elixir_prebuilt(
    name = "elixir_build",
    srcs = glob(["distribution/**"]),
    root = "distribution/.rules_elixir_root",
    visibility = ["//visibility:public"],
)

elixir_toolchain(
    name = "elixir",
    elixir = ":elixir_build",
    visibility = ["//visibility:public"],
)

# A prebuilt Elixir is hermetic in the same sense an internally built one is -- fetched and
# staged by the build rather than discovered on the host -- so it registers under the same
# :elixir_internal constraint. That keeps the generated target names identical to the
# from-source path, so moving a repository between them is a MODULE.bazel edit and nothing
# else. The target name is likewise still :elixir_build, so existing references resolve.
toolchain(
    name = "toolchain",
    exec_compatible_with = [
        "//:elixir_internal",
    ],
    target_compatible_with = [
        "//:elixir_%{ELIXIR_VERSION_ID}",
    ],
    toolchain = ":elixir",
    toolchain_type = "@rules_elixir//:toolchain_type",
    visibility = ["//visibility:public"],
)
